spring:
  application:
    name: open-search
  data:
    rest:
      basePath: /api
  profiles:
    active: igs

  config:
    import:
      - classpath:openSearch.yml          # 引入 classpath 下的 common.yml
