spring:
  application:
    name: data-rest-test
  data:
    rest:
      basePath: /api
  profiles:
    active: igs
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

