spring:
  application:
    name: data-rest-test
  data:
    rest:
      basePath: /api
  config:
    import:
      - classpath:datasource.yml
  aop:
    auto: false
    proxy-target-class: true
  cache:
    jcache:
      enabled: false

logging:
  level:
    com:
      example: DEBUG
