spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_test_dev
    username: postgres
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true

